{"cells":[{"cell_type":"code","source":"!pip3 install --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint\nimport pandas as pd\nimport twint\nimport seaborn as sns\nimport matplotlib.pyplot as plt","metadata":{"tags":[],"collapsed":true,"jupyter":{"outputs_hidden":true}},"execution_count":7,"outputs":[{"name":"stdout","text":"Collecting twint\n  Cloning https://github.com/twintproject/twint.git (to revision origin/master) to /tmp/pip-install-al9xpi0b/twint_6ff07752ba5c4381aa56665fa4fc45fb\n  Running command git clone --filter=blob:none --quiet https://github.com/twintproject/twint.git /tmp/pip-install-al9xpi0b/twint_6ff07752ba5c4381aa56665fa4fc45fb\n\u001b[33m  WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.\u001b[0m\u001b[33m\n\u001b[0m  Running command git checkout -q origin/master\n  Resolved https://github.com/twintproject/twint.git to commit origin/master\n  Preparing metadata (setup.py) ... \u001b[?25ldone\n\u001b[?25hCollecting aiohttp\n  Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)\nCollecting aiodns\n  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)\nCollecting beautifulsoup4\n  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)\nCollecting cchardet\n  Using cached cchardet-2.1.7-cp38-cp38-manylinux2010_x86_64.whl (265 kB)\nCollecting dataclasses\n  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)\nCollecting elasticsearch\n  Using cached elasticsearch-8.3.1-py3-none-any.whl (382 kB)\nCollecting pysocks\n  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)\nCollecting pandas\n  Using cached pandas-1.4.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)\nCollecting aiohttp_socks\n  Using cached aiohttp_socks-0.7.1-py3-none-any.whl (9.3 kB)\nCollecting schedule\n  Using cached schedule-1.1.0-py2.py3-none-any.whl (10 kB)\nCollecting geopy\n  Using cached geopy-2.2.0-py3-none-any.whl (118 kB)\nCollecting fake-useragent\n  Using cached fake_useragent-0.1.11-py3-none-any.whl\nCollecting googletransx\n  Using cached googletransx-2.4.2-py3-none-any.whl\nCollecting pycares>=4.0.0\n  Using cached pycares-4.2.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (292 kB)\nCollecting multidict<7.0,>=4.5\n  Using cached multidict-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121 kB)\nCollecting charset-normalizer<3.0,>=2.0\n  Using cached charset_normalizer-2.1.0-py3-none-any.whl (39 kB)\nCollecting frozenlist>=1.1.1\n  Using cached frozenlist-1.3.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)\nCollecting attrs>=17.3.0\n  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)\nCollecting async-timeout<5.0,>=4.0.0a3\n  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)\nCollecting aiosignal>=1.1.2\n  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)\nCollecting yarl<2.0,>=1.0\n  Using cached yarl-1.7.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (308 kB)\nCollecting python-socks[asyncio]<3.0.0,>=2.0.0\n  Using cached python_socks-2.0.3-py3-none-any.whl (49 kB)\nCollecting soupsieve>1.2\n  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)\nCollecting elastic-transport<9,>=8\n  Using cached elastic_transport-8.1.2-py3-none-any.whl (59 kB)\nCollecting geographiclib<2,>=1.49\n  Using cached geographiclib-1.52-py3-none-any.whl (38 kB)\nCollecting requests\n  Using cached requests-2.28.1-py3-none-any.whl (62 kB)\nCollecting numpy>=1.18.5\n  Using cached numpy-1.23.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)\nCollecting pytz>=2020.1\n  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)\nCollecting python-dateutil>=2.8.1\n  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)\nCollecting certifi\n  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)\nCollecting urllib3<2,>=1.26.2\n  Using cached urllib3-1.26.11-py2.py3-none-any.whl (139 kB)\nCollecting cffi>=1.5.0\n  Using cached cffi-1.15.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (442 kB)\nCollecting six>=1.5\n  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)\nCollecting idna>=2.0\n  Using cached idna-3.3-py3-none-any.whl (61 kB)\nCollecting pycparser\n  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)\nBuilding wheels for collected packages: twint\n  Building wheel for twint (setup.py) ... \u001b[?25ldone\n\u001b[?25h  Created wheel for twint: filename=twint-2.1.21-py3-none-any.whl size=38871 sha256=b13f46ea2b3f5a31372b4e0c005d72aa3ec6ab55f4b6d204178e5026db7508af\n  Stored in directory: /tmp/pip-ephem-wheel-cache-i06pltel/wheels/82/67/14/5495652787d3c55288164de4234c0712a1f785a64f61f1ea70\nSuccessfully built twint\nInstalling collected packages: pytz, python-socks, geographiclib, fake-useragent, dataclasses, cchardet, urllib3, soupsieve, six, schedule, pysocks, pycparser, numpy, multidict, idna, geopy, frozenlist, charset-normalizer, certifi, attrs, async-timeout, yarl, requests, python-dateutil, elastic-transport, cffi, beautifulsoup4, aiosignal, pycares, pandas, googletransx, elasticsearch, aiohttp, aiohttp_socks, aiodns, twint\n\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\nredshift-connector 2.0.900 requires pytz<2021.9,>=2020.1, but you have pytz 2022.1 which is incompatible.\nredshift-connector 2.0.900 requires requests<2.26.1,>=2.23.0, but you have requests 2.28.1 which is incompatible.\npythonwhat 2.23.1 requires dill~=0.2.7.1, but you have dill 0.3.3 which is incompatible.\npythonwhat 2.23.1 requires jinja2~=2.10, but you have jinja2 3.0.1 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0mSuccessfully installed aiodns-3.0.0 aiohttp-3.8.1 aiohttp_socks-0.7.1 aiosignal-1.2.0 async-timeout-4.0.2 attrs-21.4.0 beautifulsoup4-4.11.1 cchardet-2.1.7 certifi-2022.6.15 cffi-1.15.1 charset-normalizer-2.1.0 dataclasses-0.6 elastic-transport-8.1.2 elasticsearch-8.3.1 fake-useragent-0.1.11 frozenlist-1.3.0 geographiclib-1.52 geopy-2.2.0 googletransx-2.4.2 idna-3.3 multidict-6.0.2 numpy-1.23.1 pandas-1.4.3 pycares-4.2.1 pycparser-2.21 pysocks-1.7.1 python-dateutil-2.8.2 python-socks-2.0.3 pytz-2022.1 requests-2.28.1 schedule-1.1.0 six-1.16.0 soupsieve-2.3.2.post1 twint-2.1.21 urllib3-1.26.11 yarl-1.7.2\n--- Logging error ---\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 177, in emit\n    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1752, in print\n    extend(render(renderable, render_options))\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1390, in render\n    for render_output in iter_render:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n    for line in lines:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py\", line 245, in split_lines\n    for segment in segments:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1368, in render\n    renderable = rich_cast(renderable)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n    renderable = cast_method()\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n    pip_cmd = get_best_invocation_for_this_pip()\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n    if found_executable and os.path.samefile(\n  File \"/usr/lib/python3.8/genericpath.py\", line 101, in samefile\n    s2 = os.stat(f2)\nFileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'\nCall stack:\n  File \"/usr/local/bin/pip3\", line 8, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py\", line 70, in main\n    return command.main(cmd_args)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 101, in main\n    return self._main(args)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n    self.handle_pip_version_check(options)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py\", line 148, in handle_pip_version_check\n    pip_self_version_check(session, options)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 237, in pip_self_version_check\n    logger.info(\"[present-rich] %s\", upgrade_prompt)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1446, in info\n    self._log(INFO, msg, args, **kwargs)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1589, in _log\n    self.handle(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1599, in handle\n    self.callHandlers(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1661, in callHandlers\n    hdlr.handle(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 954, in handle\n    self.emit(record)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 179, in emit\n    self.handleError(record)\nMessage: '[present-rich] %s'\nArguments: (UpgradePrompt(old='22.1.2', new='22.2'),)\n","output_type":"stream"}],"id":"76380202-4638-42ef-9628-9b00dce8dca8"},{"cell_type":"code","source":"!pip install nest_asyncio","metadata":{"tags":[],"collapsed":true,"jupyter":{"outputs_hidden":true}},"execution_count":8,"outputs":[{"name":"stdout","text":"Collecting nest_asyncio\n  Using cached nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)\nInstalling collected packages: nest_asyncio\nSuccessfully installed nest_asyncio-1.5.5\n\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/nest_asyncio.py already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/nest_asyncio-1.5.5.dist-info already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/__pycache__ already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m--- Logging error ---\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 177, in emit\n    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1752, in print\n    extend(render(renderable, render_options))\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1390, in render\n    for render_output in iter_render:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n    for line in lines:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py\", line 245, in split_lines\n    for segment in segments:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1368, in render\n    renderable = rich_cast(renderable)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n    renderable = cast_method()\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n    pip_cmd = get_best_invocation_for_this_pip()\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n    if found_executable and os.path.samefile(\n  File \"/usr/lib/python3.8/genericpath.py\", line 101, in samefile\n    s2 = os.stat(f2)\nFileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'\nCall stack:\n  File \"/usr/local/bin/pip\", line 8, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py\", line 70, in main\n    return command.main(cmd_args)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 101, in main\n    return self._main(args)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n    self.handle_pip_version_check(options)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py\", line 148, in handle_pip_version_check\n    pip_self_version_check(session, options)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 237, in pip_self_version_check\n    logger.info(\"[present-rich] %s\", upgrade_prompt)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1446, in info\n    self._log(INFO, msg, args, **kwargs)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1589, in _log\n    self.handle(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1599, in handle\n    self.callHandlers(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1661, in callHandlers\n    hdlr.handle(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 954, in handle\n    self.emit(record)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 179, in emit\n    self.handleError(record)\nMessage: '[present-rich] %s'\nArguments: (UpgradePrompt(old='22.1.2', new='22.2'),)\n","output_type":"stream"}],"id":"a264f085-ffb3-45c5-88f9-60dd76dacfb0"},{"cell_type":"code","source":"try:#check if the file exist so you dont have to scrap from begining\n    df = pd.read_csv('tweets.csv') \n    df = df.drop(df.columns[0], axis=1)\n    df['date'] = pd.to_datetime(df['date'])\n    date = max(df['date'])\n    date = str(date).split(' ')[0] #get the date in the string format for twint\nexcept:\n    print('No tweets file')\ndf.shape","metadata":{},"execution_count":9,"outputs":[{"execution_count":9,"output_type":"execute_result","data":{"text/plain":"(158062, 37)"},"metadata":{}}],"id":"e4ff2fb9-6aa5-4d90-b5d9-11a03086b5a3"},{"cell_type":"code","source":"date","metadata":{},"execution_count":10,"outputs":[{"execution_count":10,"output_type":"execute_result","data":{"text/plain":"'2022-07-26'"},"metadata":{}}],"id":"5704afd5-60bd-42bc-9602-964c010c836f"},{"cell_type":"code","source":"import nest_asyncio\nnest_asyncio.apply()","metadata":{},"execution_count":11,"outputs":[],"id":"9be682b2-b802-47f4-9829-f85e2379c0fc"},{"cell_type":"code","source":"c = twint.Config()\nc.Search = ['Formula 1']\nc.Limit = 200000\nc.Since = date\nc.Store_csv = True\nc.Output = 'new_tweets.csv'\nc.Hide_output = True\ntwint.run.Search(c)","metadata":{},"execution_count":12,"outputs":[{"name":"stdout","text":"[!] No more data! Scraping will stop now.\nfound 0 deleted tweets in this search.\n","output_type":"stream"}],"id":"22653489-62dd-4492-801e-0122c5a08d1c"},{"cell_type":"code","source":"df1 = pd.read_csv('new_tweets.csv')\ndf1['date'] = pd.to_datetime(df1['date'])\ndate = max(df1['date'])\ndate = str(date).split(' ')[0] \ndf1['tweet']\ndate","metadata":{"collapsed":true,"jupyter":{"outputs_hidden":true},"tags":[]},"execution_count":14,"outputs":[{"execution_count":14,"output_type":"execute_result","data":{"text/plain":"'2022-07-27'"},"metadata":{}}],"id":"90adc667-7d5a-4638-9c12-00564dce05a8"},{"cell_type":"code","source":"tweets = pd.concat([df, df1]) #mergin both df so you have only one\ntweets = tweets.drop_duplicates()\ntweets.shape","metadata":{},"execution_count":15,"outputs":[{"execution_count":15,"output_type":"execute_result","data":{"text/plain":"(164653, 37)"},"metadata":{}}],"id":"e2e82a92-eac2-4b78-909a-8aa8e10254bc"},{"cell_type":"code","source":"tweets = pd.concat([df, df1]) #mergin both df so you have only one\ntweets = tweets.drop_duplicates()\ntweets.to_csv('tweets.csv', index=False)","metadata":{"collapsed":true,"jupyter":{"outputs_hidden":true},"tags":[]},"execution_count":16,"outputs":[],"id":"e9dbe0c5-90e5-41af-a84c-3b048e2a7dcc"},{"cell_type":"markdown","source":"**Filter the new tweets from the old ones to not double translate** ","metadata":{},"id":"1c28d9e9-a483-4fd1-a714-111566b58b1e"},{"cell_type":"code","source":"df_t = pd.read_csv('tweets_translated.csv')\ndf_t['time_stamp'] = df_t['date'] + ' ' + df_t['time']\ndf_t['time_stamp'] = pd.to_datetime(df_t['time_stamp'])\ndate = max(df_t['time_stamp'])\ndate\ndf_t.shape","metadata":{"collapsed":true,"jupyter":{"outputs_hidden":true},"tags":[]},"execution_count":17,"outputs":[{"execution_count":17,"output_type":"execute_result","data":{"text/plain":"(67773, 41)"},"metadata":{}}],"id":"08d9fbe2-c34b-45cb-9d15-ec13d0356a93"},{"cell_type":"code","source":"df1 = pd.read_csv('new_tweets.csv')\ndf1['time_stamp'] = df1['date'] + ' ' + df1['time']\ndf1['time_stamp'] = pd.to_datetime(df1['time_stamp'])\nnew = df1[df1['time_stamp'] > date]\nnew.shape","metadata":{"collapsed":true,"jupyter":{"outputs_hidden":true},"tags":[]},"execution_count":19,"outputs":[{"execution_count":19,"output_type":"execute_result","data":{"text/plain":"(10807, 37)"},"metadata":{}}],"id":"7c6664d2-e492-4223-ad64-7d195a57acd2"},{"cell_type":"code","source":"!pip install deep_translator","metadata":{"collapsed":true,"jupyter":{"outputs_hidden":true},"tags":[]},"execution_count":20,"outputs":[{"name":"stdout","text":"Collecting deep_translator\n  Downloading deep_translator-1.8.3-py3-none-any.whl (29 kB)\nCollecting beautifulsoup4<5.0.0,>=4.9.1\n  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)\nCollecting requests<3.0.0,>=2.23.0\n  Using cached requests-2.28.1-py3-none-any.whl (62 kB)\nCollecting soupsieve>1.2\n  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)\nCollecting charset-normalizer<3,>=2\n  Using cached charset_normalizer-2.1.0-py3-none-any.whl (39 kB)\nCollecting certifi>=2017.4.17\n  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)\nCollecting urllib3<1.27,>=1.21.1\n  Using cached urllib3-1.26.11-py2.py3-none-any.whl (139 kB)\nCollecting idna<4,>=2.5\n  Using cached idna-3.3-py3-none-any.whl (61 kB)\nInstalling collected packages: urllib3, soupsieve, idna, charset-normalizer, certifi, requests, beautifulsoup4, deep_translator\n\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\nredshift-connector 2.0.900 requires pytz<2021.9,>=2020.1, but you have pytz 2022.1 which is incompatible.\nredshift-connector 2.0.900 requires requests<2.26.1,>=2.23.0, but you have requests 2.28.1 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0mSuccessfully installed beautifulsoup4-4.11.1 certifi-2022.6.15 charset-normalizer-2.1.0 deep_translator-1.8.3 idna-3.3 requests-2.28.1 soupsieve-2.3.2.post1 urllib3-1.26.11\n\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/urllib3 already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/urllib3-1.26.11.dist-info already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/soupsieve already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/soupsieve-2.3.2.post1.dist-info already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/idna already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/idna-3.3.dist-info already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/charset_normalizer already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/charset_normalizer-2.1.0.dist-info already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/certifi already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/certifi-2022.6.15.dist-info already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/requests already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/requests-2.28.1.dist-info already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/bs4 already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/beautifulsoup4-4.11.1.dist-info already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Target directory /home/repl/.local/lib/python3.8/site-packages/bin already exists. Specify --upgrade to force replacement.\u001b[0m\u001b[33m\n\u001b[0m--- Logging error ---\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 177, in emit\n    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1752, in print\n    extend(render(renderable, render_options))\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1390, in render\n    for render_output in iter_render:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n    for line in lines:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py\", line 245, in split_lines\n    for segment in segments:\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1368, in render\n    renderable = rich_cast(renderable)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n    renderable = cast_method()\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n    pip_cmd = get_best_invocation_for_this_pip()\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n    if found_executable and os.path.samefile(\n  File \"/usr/lib/python3.8/genericpath.py\", line 101, in samefile\n    s2 = os.stat(f2)\nFileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'\nCall stack:\n  File \"/usr/local/bin/pip\", line 8, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py\", line 70, in main\n    return command.main(cmd_args)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 101, in main\n    return self._main(args)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n    self.handle_pip_version_check(options)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py\", line 148, in handle_pip_version_check\n    pip_self_version_check(session, options)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 237, in pip_self_version_check\n    logger.info(\"[present-rich] %s\", upgrade_prompt)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1446, in info\n    self._log(INFO, msg, args, **kwargs)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1589, in _log\n    self.handle(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1599, in handle\n    self.callHandlers(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1661, in callHandlers\n    hdlr.handle(record)\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 954, in handle\n    self.emit(record)\n  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 179, in emit\n    self.handleError(record)\nMessage: '[present-rich] %s'\nArguments: (UpgradePrompt(old='22.1.2', new='22.2'),)\n","output_type":"stream"}],"id":"1028e5cd-641f-4887-85fa-86bdab5fa249"},{"cell_type":"code","source":"# Translate tweets for better analysis\nfrom deep_translator import GoogleTranslator\nnew['tweet'] = new['tweet'].apply(lambda tweet: GoogleTranslator(source='auto', target='en').translate(tweet))\nnew['tweet']","metadata":{"tags":[]},"execution_count":21,"outputs":[{"execution_count":21,"output_type":"execute_result","data":{"text/plain":"118599    @marca @Carlossainz55 RIDICULOUS .... that's h...\n118600    @pkligerman @SvenPretsch @F1 @IndyCar @NASCAR ...\n118601    @GBrown84 @F1 It's written in my will to have ...\n118602    The hell of Formula 1 workers in Montmeló: no ...\n118603    @mohamedriyad96 @hikarievil I kno sorry formul...\n                                ...                        \n133237       @spowcardow @F1 9 championships in one image 🐐\n133238    I think I have a crush on this girl who is als...\n133239           @F1 Always King 👑  https://t.co/P3VL2bsqyS\n133240    @blog_formula1 @portoseguro Do you have a gene...\n133241                         @F1 Nando schooling Hamilton\nName: tweet, Length: 10807, dtype: object"},"metadata":{}}],"id":"020f2f2c-ffc1-41d7-8885-7cf4328f02a0"},{"cell_type":"code","source":"tweets = pd.concat([new, df_t]) #mergin both df so you have only one\ntweets = tweets.drop_duplicates()\ntweets['tweet']","metadata":{},"execution_count":22,"outputs":[{"execution_count":22,"output_type":"execute_result","data":{"text/plain":"118599    @marca @Carlossainz55 RIDICULOUS .... that's h...\n118600    @pkligerman @SvenPretsch @F1 @IndyCar @NASCAR ...\n118601    @GBrown84 @F1 It's written in my will to have ...\n118602    The hell of Formula 1 workers in Montmeló: no ...\n118603    @mohamedriyad96 @hikarievil I kno sorry formul...\n                                ...                        \n67768     @elonmusk tesla should compete in Formula 1 El...\n67769     @F1 What Every Ferrari F1 Driver Is Scared Of ...\n67770     @F1 @ScuderiaFerrari Grande Charles,  grande C...\n67771     Pierre said the only French food Yuki hasn’t t...\n67772     @ImAProblemWR @BankruptJokerst @blog_formula1 ...\nName: tweet, Length: 73305, dtype: object"},"metadata":{}}],"id":"f52475b2-9a41-4e29-8405-bca1cddf21ec"},{"cell_type":"code","source":"tweets = pd.concat([new, df_t]) #mergin both df so you have only one\ntweets = tweets.drop_duplicates()\ntweets.to_csv('tweets_translated.csv', index=False)","metadata":{},"execution_count":23,"outputs":[],"id":"05b1a1b5-7bc2-42e5-a703-92850caaf18a"},{"cell_type":"code","source":"data = pd.read_csv('tweets_translated.csv')\ndata.info()","metadata":{},"execution_count":24,"outputs":[{"name":"stdout","text":"<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 73305 entries, 0 to 73304\nData columns (total 42 columns):\n #   Column           Non-Null Count  Dtype  \n---  ------           --------------  -----  \n 0   Unnamed: 0.4     73305 non-null  int64  \n 1   id               73305 non-null  int64  \n 2   conversation_id  73305 non-null  int64  \n 3   created_at       73305 non-null  object \n 4   date             73305 non-null  object \n 5   time             73305 non-null  object \n 6   timezone         73305 non-null  int64  \n 7   user_id          73305 non-null  int64  \n 8   username         73305 non-null  object \n 9   name             73304 non-null  object \n 10  place            33 non-null     object \n 11  tweet            73305 non-null  object \n 12  language         73305 non-null  object \n 13  mentions         73305 non-null  object \n 14  urls             73305 non-null  object \n 15  photos           73305 non-null  object \n 16  replies_count    73305 non-null  int64  \n 17  retweets_count   73305 non-null  int64  \n 18  likes_count      73305 non-null  int64  \n 19  hashtags         73305 non-null  object \n 20  cashtags         73305 non-null  object \n 21  link             73305 non-null  object \n 22  retweet          73305 non-null  bool   \n 23  quote_url        2263 non-null   object \n 24  video            73305 non-null  int64  \n 25  thumbnail        12942 non-null  object \n 26  near             0 non-null      float64\n 27  geo              0 non-null      float64\n 28  source           0 non-null      float64\n 29  user_rt_id       0 non-null      float64\n 30  user_rt          0 non-null      float64\n 31  retweet_id       0 non-null      float64\n 32  reply_to         73305 non-null  object \n 33  retweet_date     0 non-null      float64\n 34  translate        0 non-null      float64\n 35  trans_src        0 non-null      float64\n 36  trans_dest       0 non-null      float64\n 37  time_stamp       73305 non-null  object \n 38  Unnamed: 0.3     67773 non-null  float64\n 39  Unnamed: 0.2     56566 non-null  float64\n 40  Unnamed: 0.1     52111 non-null  float64\n 41  Unnamed: 0       52111 non-null  float64\ndtypes: bool(1), float64(14), int64(9), object(18)\nmemory usage: 23.0+ MB\n","output_type":"stream"}],"id":"a42591ea-e7d9-40e5-9b2f-df06eb322f26"}],"metadata":{"language_info":{"name":"python","version":"3.8.10","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"editor":"DataCamp Workspace"},"nbformat":4,"nbformat_minor":5}